baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Michal Wyka'
theme = "MWykaTheme"
[menu]
  [[menu.main]]
    name = "What I Do"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2